from .categorias import CategoriaSerializador, CategoriaListSerializador
from .capas import CapaListSerializador, CapaSerializador
from .atributos import AtributoSerializador
from .parametros import ParametroSerializador, ParametroListSerializador
from .casos import CasosListSerializador, CasosSerializador
from .usuarios import UsuarioSerializador, UsuarioListSerializador, UserSerializer, UserDetailsSerializer
from .tipologia import TipologiaSerializador, TipologiaListSerializador
from .territorio import TerritorioSerializador, TerritorioListSerializador
from .geounidad import GeoUnidadSerializador, GeoUnidadListSerializador
from .comunidad import ComunidadSerializador, ComunidadListSerializador
from .riesgos import RiesgosSerializador, RiesgosListSerializador, RiesgosGeoUnidadSerializador
from .vivienda import ViviendaSerializador, ViviendaListSerializador
from .centrosaludemergencia import CentroSaludEmergenciaSerializador, CentroSaludEmergenciaListSerializador
from .centroeducativo import CentroEducativoSerializador, CentroEducativoListSerializador
from .consejocomunal import ConsejoComunalSerializador, ConsejoComunalListSerializador			
from .censo import CensoSerializador, CensoListSerializador			