# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 23:08
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('Point', 'Point'), ('Polygon', 'Polygon'), ('LineString', 'LineString'), ('Text', 'Text'), ('Int', 'Int'), ('Float', 'Float'), ('MultiPolygon', 'MultiPolygon'), ('MultiLineString', 'MultiLineString'), ('Image', 'Image'), ('Email', 'Email'), ('Date', 'Date'), ('DateTime', 'DateTime')], max_length=30)),
                ('descripcion', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('Point', 'Point'), ('Polygon', 'Polygon'), ('LineString', 'LineString'), ('MultiPolygon', 'MultiPolygon'), ('MultiLineString', 'MultiLineString')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Casos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField(blank=True)),
                ('hora', models.TimeField(blank=True)),
                ('fecha_creado', models.DateField(blank=True)),
                ('hora_creado', models.TimeField(blank=True)),
                ('visible', models.BooleanField(default=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('registro', models.IntegerField(null=True)),
                ('capa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Casos', to='capas.Capas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Casos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoUnidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.FloatField(default=0)),
                ('amenaza', models.FloatField(default=0)),
                ('vulnerabilidad', models.FloatField(default=0)),
                ('riesgo', models.FloatField(default=0)),
                ('fuente', models.CharField(max_length=255, null=True)),
                ('anyo', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='capas.Casos')),
            ],
        ),
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('tipo', models.CharField(choices=[('Text', 'Text'), ('Int', 'Int'), ('Float', 'Float'), ('Image', 'Image'), ('Email', 'Email'), ('Date', 'Date'), ('DateTime', 'DateTime')], max_length=30)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='capas.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Territorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=60)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('poblacion_censo', models.IntegerField(default=0)),
                ('poblacion_determinada', models.IntegerField(default=0)),
                ('estado', models.CharField(blank=True, max_length=255)),
                ('municipio', models.CharField(blank=True, max_length=255)),
                ('parroquia', models.CharField(blank=True, max_length=255)),
                ('parentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencias', to='capas.Territorio')),
            ],
        ),
        migrations.CreateModel(
            name='TipologiaConstructiva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('estandar', models.CharField(max_length=255)),
                ('anyo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='geounidad',
            name='territorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geounidades', to='capas.Territorio'),
        ),
        migrations.AddField(
            model_name='capas',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capas', to='capas.Categoria'),
        ),
        migrations.AddField(
            model_name='atributos',
            name='capa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='capas.Capas'),
        ),
    ]
