# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('PUNTO', 'PUNTO'), ('POLIGONO', 'POLIGONO'), ('LINEA', 'LINEA'), ('TEXTO', 'TEXTO'), ('ENTERO', 'ENTERO'), ('FLOTANTE', 'FLOTANTE')], max_length=30)),
                ('descripcion', models.CharField(max_length=80)),
                ('capa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capas.Capas')),
            ],
        ),
    ]
