# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-05 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casos',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='casos',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
