# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 16:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geounidad',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='geounidad',
            name='anyo',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='geounidad',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
