# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suceso',
            name='hora',
        ),
    ]
