# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 18:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0002_auto_20180117_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('poblacion', models.IntegerField(default=0)),
                ('area', models.FloatField(default=0.0)),
                ('indiceVulnerabilidad', models.FloatField(default=0)),
                ('indiceAmenaza', models.FloatField(default=0)),
                ('indiceRiesgo', models.FloatField(default=0)),
                ('estatus_social', models.CharField(blank=True, max_length=255, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('geounidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='capas.GeoUnidad')),
                ('terrtitorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='capas.Territorio')),
                ('tipologiaConstructiva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='capas.TipologiaConstructiva')),
            ],
        ),
        migrations.CreateModel(
            name='Riesgos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indiceVulnerabilidad', models.FloatField(default=0)),
                ('indiceAmenaza', models.FloatField(default=0)),
                ('indiceRiesgo', models.FloatField(default=0)),
                ('anyo', models.IntegerField(default=1900)),
                ('fuente', models.CharField(blank=True, max_length=255, null=True)),
                ('geounidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='capas.GeoUnidad')),
            ],
        ),
    ]
