# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0002_remove_suceso_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='grupos',
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Usuario', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='institucion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
