# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0003_comunidad_riesgos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geounidad',
            name='anyo',
            field=models.IntegerField(default=1900),
        ),
    ]
