# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0004_auto_20180117_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geounidad',
            old_name='amenaza',
            new_name='indiceAmenaza',
        ),
        migrations.RenameField(
            model_name='geounidad',
            old_name='riesgo',
            new_name='indiceRiesgo',
        ),
        migrations.RenameField(
            model_name='geounidad',
            old_name='vulnerabilidad',
            new_name='indiceVulnerabilidad',
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='geounidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='capas.GeoUnidad'),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='terrtitorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='capas.Territorio'),
        ),
        migrations.AlterField(
            model_name='comunidad',
            name='tipologiaConstructiva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comunidades', to='capas.TipologiaConstructiva'),
        ),
    ]
