# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0004_auto_20171214_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
