# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0005_auto_20180117_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='riesgos',
            name='indiceModificado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
