# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0006_riesgos_indicemodificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='riesgos',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
