# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0007_riesgos_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunidad',
            old_name='estatus_social',
            new_name='statusSocial',
        ),
    ]
