# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 21:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0009_auto_20180119_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsejoComunal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('poblacionDeterminada', models.IntegerField(default=0, null=True)),
                ('poblacionCenso', models.IntegerField(default=0, null=True)),
                ('area', models.FloatField(default=0, null=True)),
                ('servicios', models.CharField(blank=True, max_length=255, null=True)),
                ('indiceVulnerabilidad', models.IntegerField(default=0, null=True)),
                ('indiceAmenaza', models.IntegerField(default=0, null=True)),
                ('indiceRiesgo', models.IntegerField(default=0, null=True)),
                ('comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consejoComunal', to='capas.Comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('direccion', models.CharField(max_length=255)),
                ('anyo_construccion', models.IntegerField(default=1900)),
                ('pisos', models.IntegerField(default=1)),
                ('tipoEstructura', models.CharField(blank=True, max_length=255, null=True)),
                ('uso', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.FloatField(default=0, null=True)),
                ('indiceOcupacional', models.FloatField(default=0, null=True)),
                ('numHabitacion', models.IntegerField(default=0)),
                ('numAmbientes', models.IntegerField(default=1)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoParedes', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoPiso', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoTecho', models.CharField(blank=True, max_length=255, null=True)),
                ('numBanos', models.IntegerField(default=0)),
                ('aguasBlancas', models.CharField(max_length=2)),
                ('aguasServidas', models.CharField(max_length=2)),
                ('gas', models.CharField(blank=True, max_length=255, null=True)),
                ('sistemaElectrico', models.CharField(blank=True, max_length=255, null=True)),
                ('aseo', models.CharField(blank=True, max_length=255, null=True)),
                ('telefonia', models.CharField(blank=True, max_length=255, null=True)),
                ('transporte', models.CharField(blank=True, max_length=255, null=True)),
                ('numFamilias', models.IntegerField(default=0)),
                ('numHabitantes', models.IntegerField(default=0)),
                ('numNinos', models.IntegerField(default=0)),
                ('numAdultos', models.IntegerField(default=0)),
                ('numTercera', models.IntegerField(default=0)),
                ('numMasculino', models.IntegerField(default=0)),
                ('numFemenino', models.IntegerField(default=0)),
                ('nacionalidad', models.CharField(blank=True, max_length=255, null=True)),
                ('indiceVulnerabilidad', models.IntegerField(default=0, null=True)),
                ('indiceAmenaza', models.IntegerField(default=0, null=True)),
                ('indiceRiesgo', models.IntegerField(default=0, null=True)),
                ('comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viviendas', to='capas.Comunidad')),
                ('consejoComunal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viviendas', to='capas.ConsejoComunal')),
            ],
        ),
    ]
