# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 22:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0010_consejocomunal_vivienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
