# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0012_vivienda_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='aguasBlancas',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='aguasServidas',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='indiceAmenaza',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='indiceRiesgo',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='indiceVulnerabilidad',
            field=models.FloatField(default=0, null=True),
        ),
    ]
