# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 08:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0013_auto_20180119_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroEducativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('anyo_construccion', models.IntegerField(default=1900)),
                ('area', models.FloatField(default=0, null=True)),
                ('uso', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoPisos', models.CharField(blank=True, max_length=255, null=True)),
                ('indiceOcupacional', models.FloatField(default=0, null=True)),
                ('codigoDEA', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula', models.IntegerField(default=1, null=True)),
                ('tipoEscuela', models.CharField(blank=True, max_length=255, null=True)),
                ('turno', models.CharField(blank=True, max_length=255, null=True)),
                ('numedificios', models.IntegerField(default=1, null=True)),
                ('numpisos', models.IntegerField(default=1, null=True)),
                ('tipoEdificacion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipoDependencia', models.CharField(blank=True, max_length=255, null=True)),
                ('danyo', models.CharField(blank=True, max_length=255, null=True)),
                ('indiceVulnerabilidad', models.FloatField(default=0, null=True)),
                ('indiceAmenaza', models.FloatField(default=0, null=True)),
                ('indiceRiesgo', models.FloatField(default=0, null=True)),
                ('comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centroseducativos', to='capas.Comunidad')),
                ('tipologiaConstructiva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centroseducativos', to='capas.TipologiaConstructiva')),
            ],
        ),
        migrations.CreateModel(
            name='CentroSaludEmergencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('anyo_construccion', models.IntegerField(default=1900, null=True)),
                ('poblacionDiaria', models.IntegerField(default=0, null=True)),
                ('numCamas', models.IntegerField(default=0, null=True)),
                ('capacidad', models.IntegerField(default=0, null=True)),
                ('horarioAtencion', models.CharField(blank=True, max_length=255, null=True)),
                ('serviciosMedicos', models.CharField(blank=True, max_length=255, null=True)),
                ('numpisos', models.IntegerField(default=1, null=True)),
                ('numedificios', models.IntegerField(default=1, null=True)),
                ('area', models.FloatField(default=0, null=True)),
                ('indiceVulnerabilidad', models.FloatField(default=0, null=True)),
                ('indiceAmenaza', models.FloatField(default=0, null=True)),
                ('indiceRiesgo', models.FloatField(default=0, null=True)),
                ('comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centrosaludemergencia', to='capas.Comunidad')),
                ('tipologiaConstructiva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centrosaludemergencia', to='capas.TipologiaConstructiva')),
            ],
        ),
        migrations.RenameField(
            model_name='vivienda',
            old_name='pisos',
            new_name='numpisos',
        ),
        migrations.AddField(
            model_name='vivienda',
            name='tipologiaConstructiva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viviendas', to='capas.TipologiaConstructiva'),
        ),
        migrations.AlterField(
            model_name='consejocomunal',
            name='comunidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consejoscomunales', to='capas.Comunidad'),
        ),
    ]
