# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0015_auto_20180120_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centroeducativo',
            name='comunidad',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='centroseducativos', to='capas.Comunidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='centrosaludemergencia',
            name='comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centrosaludemergencia', to='capas.Comunidad'),
        ),
    ]
