# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0016_auto_20180120_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centroeducativo',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='centrosaludemergencia',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
