# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0017_auto_20180120_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Censo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('totalFamilias', models.IntegerField(default=0)),
                ('totalHabitantes', models.IntegerField(default=0)),
                ('totalViviendas', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='consejocomunal',
            name='representante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='consejocomunal',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='censo',
            name='consejocomunal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='censo', to='capas.ConsejoComunal'),
        ),
    ]
