# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capas', '0018_auto_20180120_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='censo',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
